### PR TITLE
Add OAuth2 Support, remove ClientLogin support

### PR DESCRIPTION
**Pull request by CardboardMechanic**
I've added support for simply passing in an OAuth2 token. This means developers no longer need to pass around usernames and passwords to use a deprecated login method. This has worked well for me using the omniauth-google-oauth2 gem.

### CODE REVIEW

**Comment by LeakyBucket** [comment]
Thanks for all the work.

However, I would like to preserve the "old school" auth method as I think it has value when using the tool from the command line.  Whether that happens much or not is another issue.  It would be nice to see both in parallel as OAuth is really how most people will be doing this.

I'll see if I can reconcile the two when I get some time.

I appreciate the contributions though.  As you could probably tell from the activity and my taking almost a month to see this I've been rather busy lately.

**Comment by LeakyBucket** [comment]
Screw it.  I'm probably the only person who was using this in a non-web environment anyway.

**Comment by CardboardMechanic** [comment]
@LeakyBucket we probably should also look in to supporting what Google calls the Hybrid Auth which is a combination of OpenID for "logging in" and 2-legged OAuth for all the stuff this gem takes care of. The advantage of using the hybrid is that the individual user doesn't get prompted to grant privileges that the domain admin has already granted when installing the Google App. 

OAuth2 still works just fine, but causes that extra approval process. I've done this work but it's embedded in my current project. I'd be happy to pull it out and in to this gem if you want it.

**Comment by LeakyBucket** [comment]
@TildeWill That would be most welcome.

**Pull request merged**
